---
  - name: Setup Django Server
    hosts: nuke
    become: true
    become_method: sudo
    vars_files:
      - vars/main.yaml

    tasks:

    - name: Install Python pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install Virtual env
      apt:
        name: python3.10-venv
        state: present
        update_cache: yes

    - name: Perform Cleanup
      shell: |
        pkill -f 'python3 manage.py' &
        
        rm -rf /home/ubuntu/app
      ignore_errors: true
        


    - name: pull branch master
      git:
        repo: git@github.com:unuefeejovwoke/Nuke_api.git
        dest: /home/ubuntu/app
        accept_hostkey: yes
        key_file: /home/ubuntu/.ssh/id_rsa

    - name: Switch Git branch
      git:
        repo: /home/ubuntu/app
        dest: /home/ubuntu/app
        version: dev


    - name: Complete Setup
      shell: |
        sudo rm -rf venv
        cd {{ work_dir }}
        python3 -m venv venv
        . venv/bin/activate
        
        pip install --no-cache-dir -r requirements.txt --require-virtualenv -v
        mkdir static
        python3 manage.py migrate
        rm staticfiles/staticfiles.json
       
        python3 manage.py collectstatic --no-input
        python3 manage.py runserver  0.0.0.0:8000 &
      # become: false
      # become_user: ubuntu
      # become_flags: '-t'


